config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/search', to: 'home#search', as: :search_repos
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def search
    @repos, @error = GitHubService.new(search_params[:username]).call
    render :index
  end

  private

  def search_params
    params.permit(:username)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/response_helper.rb
# frozen_string_literal: true

module ResponseHelper
  def blank_username_response
    [EMPTY_REPOS, 'blank username']
  end

  def empty_response
    [EMPTY_REPOS, 'not able to get response from github, try again..']
  end

  def username_not_found_response
    [EMPTY_REPOS, 'username not found']
  end

  def failure_response(response)
    [EMPTY_REPOS, format_message("unsuccessful response from github, http_code:#{response.code}")]
  end

  def error_response(err)
    [EMPTY_REPOS, format_message(err.message)]
  end

  private

  def format_message(message)
    message.downcase
  end
end

app/views/home/index.html.erb
<h2><%= link_to 'Find GitHub Public Repos', root_path %></h2>
<%= form_tag(search_repos_path, method: :get) do %>
  <%= text_field_tag(:username, nil, placeholder: 'Enter Github username') %>
  <%= submit_tag('Search') %>
<% end %>

<% unless @repos.nil? %>
  <% if @error.present? %>
    <h3>Search failed, error message: <%= @error %></h3>
  <% else %>
    <h3>Public repos:</h3>
    <% if @repos.empty? %>
      <h5>Repos don't exists</h5>
    <% else %>
      <ol type='1'>
        <% @repos.each do |repo| %>
          <li><%= link_to repo['name'], repo['html_url'], target: '_blank' %></li>
        <% end %>
      </ol>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindRepos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>